# Generated by Django 3.2.3 on 2021-05-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_auto_20210525_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bvn', models.CharField(max_length=30)),
                ('return_date', models.CharField(max_length=30)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussd.customer')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'ordering': ['created'],
            },
        ),
    ]
